### ISSUE TITLE
Add support for podman for MacOS

### ISSUE THREAD

**Issue by xmnlab** [conda-forge/podman-feedstock#32]
### Comment:

https://github.com/conda-forge/podman-feedstock/blob/main/recipe/meta.yaml#L20

currently, podman on conda-forge is supporting just linux machines.

would it be possible to add support for macos? 
if yes, I would be happy to work on that.

thanks!

**Comment by manics** [comment]
Podman on Mac OS and Windows runs in a virtual machine, managed with the `podman machine` command:
https://podman.io/getting-started/installation

Since the build steps will therefore be very different (and in practice it's a completely separate package) I think it's best to package it as a new `podman-machine` conda-forge feedstock. What do you think?

**Comment by xmnlab** [comment]
Got it. Yep that makes sense. Thanks for your quick answer!
